# Generated by Django 5.2 on 2026-09-28 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Юридическое название')),
                ('company_type', models.CharField(choices=[('business', 'Действующий бизнес'), ('startup', 'Стартап')], default='business', max_length=20, verbose_name='Тип')),
                ('industry', models.CharField(blank=True, max_length=255, verbose_name='Сфера бизнеса')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('source', models.CharField(blank=True, choices=[('referral', 'Рекомендация'), ('inbound', 'Входящее обращение'), ('outreach', 'Собственный поиск'), ('social', 'Соцсети'), ('event', 'Мероприятие'), ('other', 'Другое')], max_length=20, verbose_name='Источник')),
                ('source_details', models.CharField(blank=True, help_text='Кто порекомендовал, какое мероприятие и т.п.', max_length=255, verbose_name='Источник — подробнее')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('analysis', 'Анализ'), ('discussion', 'Обсуждение'), ('approved', 'Одобрен'), ('negotiation', 'Переговоры'), ('contract', 'Договор'), ('partner', 'Партнёр'), ('rejected', 'Отклонён')], db_index=True, default='new', editable=False, max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Статус изменён')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CandidateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата рассмотрения')),
                ('decision', models.CharField(choices=[('rework', 'На доработку'), ('approve', 'Одобрить'), ('reject', 'Отклонить')], max_length=20, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='partners.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Решение по кандидату',
                'verbose_name_plural': 'Решения по кандидатам',
                'ordering': ('-review_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CandidateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('business_model', models.TextField(blank=True, verbose_name='Бизнес-модель')),
                ('products', models.TextField(blank=True, verbose_name='Текущий продукт / услуги')),
                ('target_audience', models.TextField(blank=True, verbose_name='Целевая аудитория')),
                ('team_info', models.TextField(blank=True, verbose_name='Команда')),
                ('market_analysis', models.TextField(blank=True, verbose_name='Анализ рынка')),
                ('development_plan', models.TextField(blank=True, verbose_name='План развития компании')),
                ('it_state', models.TextField(blank=True, verbose_name='Текущее состояние IT')),
                ('problem', models.TextField(blank=True, verbose_name='Какую проблему нужно решить')),
                ('proposed_solution', models.TextField(blank=True, verbose_name='Какое IT-решение можем предложить')),
                ('mvp_state', models.CharField(blank=True, choices=[('yes', 'Есть'), ('in_progress', 'В разработке'), ('no', 'Нет')], max_length=20, verbose_name='MVP')),
                ('revenue', models.CharField(blank=True, help_text='Если компания раскрыла, например «≈ 800 000 сом/мес»', max_length=255, verbose_name='Текущая выручка')),
                ('financial_indicator', models.CharField(blank=True, max_length=255, verbose_name='Минимальный доход / фин. показатель')),
                ('financial_transparency', models.CharField(blank=True, choices=[('high', 'Высокая — данные предоставлены'), ('partial', 'Частичная'), ('low', 'Низкая — данные скрываются')], max_length=20, verbose_name='Прозрачность финансов')),
                ('legal_risks', models.TextField(blank=True, verbose_name='Налоговые / юридические риски')),
                ('reputation', models.TextField(blank=True, verbose_name='Клиентская репутация')),
                ('risks_for_zea', models.TextField(blank=True, verbose_name='Потенциальные риски для ZEA')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера по развитию')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='partners.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Анализ кандидата',
                'verbose_name_plural': 'Анализ кандидатов',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'Новый'), ('analysis', 'Анализ'), ('discussion', 'Обсуждение'), ('approved', 'Одобрен'), ('negotiation', 'Переговоры'), ('contract', 'Договор'), ('partner', 'Партнёр'), ('rejected', 'Отклонён')], max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('new', 'Новый'), ('analysis', 'Анализ'), ('discussion', 'Обсуждение'), ('approved', 'Одобрен'), ('negotiation', 'Переговоры'), ('contract', 'Договор'), ('partner', 'Партнёр'), ('rejected', 'Отклонён')], max_length=20, verbose_name='В статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='partners.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Изменение статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ('-is_primary', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company',), name='partners_one_primary_contact')],
            },
        ),
    ]
