# Generated by Django 5.2 on 2026-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('industry', models.CharField(max_length=100, verbose_name='Сфера')),
                ('icon', models.CharField(default='building-2', max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project_type', models.CharField(max_length=100, verbose_name='Тип проекта')),
                ('technologies', models.CharField(help_text='Через запятую: Django, React, Docker', max_length=500, verbose_name='Технологии')),
                ('icon', models.CharField(default='layers', max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='code-2', max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Открыты для новых проектов', max_length=100, verbose_name='Hero бейдж')),
                ('hero_title', models.CharField(default='ZEA — разработка цифровых решений для бизнеса', max_length=200, verbose_name='Hero заголовок (строка 1)')),
                ('hero_subtitle', models.TextField(default='Создаём сайты, CRM-системы, Telegram-ботов и внутренние платформы для автоматизации бизнес-процессов.', verbose_name='Hero подзаголовок')),
                ('about_text', models.TextField(default='ZEA — мини IT-студия, которая помогает бизнесам запускать современные цифровые продукты. Мы разрабатываем сайты, CRM-системы, Telegram-ботов и решения для автоматизации процессов.', verbose_name='О компании (текст)')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/zea_studio', verbose_name='Telegram URL')),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/996700000000', verbose_name='WhatsApp URL')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/zea.studio', verbose_name='Instagram URL')),
                ('email', models.EmailField(blank=True, default='hello@zea.dev', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(help_text='Например: 5 (для счётчика) или CRM (текст)', max_length=20, verbose_name='Значение (текст)')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('suffix', models.CharField(blank=True, help_text='Например: + (отображается после числа)', max_length=5, verbose_name='Суффикс')),
                ('is_counter', models.BooleanField(default=False, verbose_name='Анимированный счётчик')),
                ('counter_target', models.PositiveIntegerField(blank=True, help_text='Только для счётчиков', null=True, verbose_name='Целевое число')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.CharField(max_length=6, verbose_name='Метка (2-3 символа)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='check-circle', max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Причина выбора',
                'verbose_name_plural': 'Почему выбирают нас',
                'ordering': ['order'],
            },
        ),
    ]
