# Generated by Django 5.2 on 2026-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='value_text',
            field=models.CharField(help_text='Например: 5 (для счётчика) или CRM (текст)', max_length=100, verbose_name='Значение (текст)'),
        ),
    ]
