# Generated by Django 5.2 on 2026-05-30 21:37

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_stat_value_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Логотип компании (400×400, WebP)', keep_meta=True, null=True, quality=90, scale=None, size=[400, 400], upload_to='partners/', verbose_name='🖼 Логотип'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Скриншот / превью проекта (1200×800, WebP)', keep_meta=True, null=True, quality=88, scale=None, size=[1200, 800], upload_to='projects/', verbose_name='📷 Скриншот проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL живого сайта (кнопка "Открыть проект")', verbose_name='🔗 Ссылка на проект'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Иллюстрация / скриншот услуги (800×600, WebP)', keep_meta=True, null=True, quality=88, scale=None, size=[800, 600], upload_to='services/', verbose_name='📷 Изображение услуги'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Квадратный логотип (80×80, WebP)', keep_meta=True, null=True, quality=90, scale=None, size=[80, 80], upload_to='tech/', verbose_name='🖼 Логотип технологии'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Опционально — иллюстрация к пункту', keep_meta=True, null=True, quality=85, scale=None, size=[600, 400], upload_to='why/', verbose_name='📷 Изображение'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.CharField(default='building-2', help_text='Используется если логотип не загружен', max_length=60, verbose_name='Иконка (lucide)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(default='layers', help_text='Используется если фото не загружено', max_length=60, verbose_name='Иконка (lucide)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='code-2', help_text='Используется если фото не загружено', max_length=60, verbose_name='Иконка (lucide)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='ZEA — мини IT-студия, которая помогает бизнесам запускать современные цифровые продукты. Мы разрабатываем сайты, CRM-системы, Telegram-ботов и решения для автоматизации процессов.', verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='ZEA — разработка цифровых решений для бизнеса', max_length=200, verbose_name='Hero заголовок'),
        ),
    ]
