# Generated by Django 5.2 on 2026-05-30 22:29

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_partner_logo_project_image_project_live_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Иконка вкладки браузера (квадрат 64×64)', keep_meta=True, null=True, quality=95, scale=None, size=[64, 64], upload_to='brand/', verbose_name='🔲 Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2024 ZEA IT Studio. All rights reserved.', max_length=200, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Основной логотип сайта (PNG/SVG → WebP, 600×200)', keep_meta=True, null=True, quality=92, scale=None, size=[600, 200], upload_to='brand/', verbose_name='🖼 Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_white',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Белая версия логотипа (необязательно)', keep_meta=True, null=True, quality=92, scale=None, size=[600, 200], upload_to='brand/', verbose_name='🖼 Логотип (белый / для тёмного фона)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание для поисковиков и соцсетей (до 320 симв.)', max_length=320, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=300, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы в поисковике (до 120 симв.)', max_length=120, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Картинка при шаринге ссылки (1200×630, WebP)', keep_meta=True, null=True, quality=88, scale=None, size=[1200, 630], upload_to='brand/', verbose_name='🌐 OG Image (превью в соцсетях)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='ZEA', max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='IT Studio', max_length=200, verbose_name='Слоган / подзаголовок бренда'),
        ),
    ]
