# Generated by Django 5.2 on 2026-05-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesettings_favicon_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='industry_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Сфера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='industry_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Сфера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='industry_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Сфера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(help_text='Через запятую: Django, React, Docker', max_length=500, null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ky',
            field=models.CharField(help_text='Через запятую: Django, React, Docker', max_length=500, null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ru',
            field=models.CharField(help_text='Через запятую: Django, React, Docker', max_length=500, null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(default='ZEA — мини IT-студия, которая помогает бизнесам запускать современные цифровые продукты. Мы разрабатываем сайты, CRM-системы, Telegram-ботов и решения для автоматизации процессов.', null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ky',
            field=models.TextField(default='ZEA — мини IT-студия, которая помогает бизнесам запускать современные цифровые продукты. Мы разрабатываем сайты, CRM-системы, Telegram-ботов и решения для автоматизации процессов.', null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(default='ZEA — мини IT-студия, которая помогает бизнесам запускать современные цифровые продукты. Мы разрабатываем сайты, CRM-системы, Telegram-ботов и решения для автоматизации процессов.', null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.CharField(blank=True, default='© 2024 ZEA IT Studio. All rights reserved.', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ky',
            field=models.CharField(blank=True, default='© 2024 ZEA IT Studio. All rights reserved.', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.CharField(blank=True, default='© 2024 ZEA IT Studio. All rights reserved.', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_en',
            field=models.CharField(default='Открыты для новых проектов', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_ky',
            field=models.CharField(default='Открыты для новых проектов', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_ru',
            field=models.CharField(default='Открыты для новых проектов', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Создаём сайты, CRM-системы, Telegram-ботов и внутренние платформы для автоматизации бизнес-процессов.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ky',
            field=models.TextField(default='Создаём сайты, CRM-системы, Telegram-ботов и внутренние платформы для автоматизации бизнес-процессов.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.TextField(default='Создаём сайты, CRM-системы, Telegram-ботов и внутренние платформы для автоматизации бизнес-процессов.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='ZEA — разработка цифровых решений для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ky',
            field=models.CharField(default='ZEA — разработка цифровых решений для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(default='ZEA — разработка цифровых решений для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Описание для поисковиков и соцсетей (до 320 симв.)', max_length=320, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ky',
            field=models.TextField(blank=True, help_text='Описание для поисковиков и соцсетей (до 320 симв.)', max_length=320, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Описание для поисковиков и соцсетей (до 320 симв.)', max_length=320, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=300, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ky',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=300, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=300, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы в поисковике (до 120 симв.)', max_length=120, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ky',
            field=models.CharField(blank=True, help_text='Заголовок страницы в поисковике (до 120 симв.)', max_length=120, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы в поисковике (до 120 симв.)', max_length=120, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='ZEA', max_length=100, null=True, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ky',
            field=models.CharField(default='ZEA', max_length=100, null=True, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(default='ZEA', max_length=100, null=True, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_en',
            field=models.CharField(blank=True, default='IT Studio', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_ky',
            field=models.CharField(blank=True, default='IT Studio', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_ru',
            field=models.CharField(blank=True, default='IT Studio', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='stat',
            name='suffix_en',
            field=models.CharField(blank=True, help_text='Например: + (отображается после числа)', max_length=5, null=True, verbose_name='Суффикс'),
        ),
        migrations.AddField(
            model_name='stat',
            name='suffix_ky',
            field=models.CharField(blank=True, help_text='Например: + (отображается после числа)', max_length=5, null=True, verbose_name='Суффикс'),
        ),
        migrations.AddField(
            model_name='stat',
            name='suffix_ru',
            field=models.CharField(blank=True, help_text='Например: + (отображается после числа)', max_length=5, null=True, verbose_name='Суффикс'),
        ),
        migrations.AddField(
            model_name='stat',
            name='value_text_en',
            field=models.CharField(help_text='Например: 5 (для счётчика) или CRM (текст)', max_length=100, null=True, verbose_name='Значение (текст)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='value_text_ky',
            field=models.CharField(help_text='Например: 5 (для счётчика) или CRM (текст)', max_length=100, null=True, verbose_name='Значение (текст)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='value_text_ru',
            field=models.CharField(help_text='Например: 5 (для счётчика) или CRM (текст)', max_length=100, null=True, verbose_name='Значение (текст)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='label_en',
            field=models.CharField(max_length=6, null=True, verbose_name='Метка (2-3 символа)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='label_ky',
            field=models.CharField(max_length=6, null=True, verbose_name='Метка (2-3 символа)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='label_ru',
            field=models.CharField(max_length=6, null=True, verbose_name='Метка (2-3 символа)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
