# Generated by Django 5.2 on 2026-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_partner_industry_en_partner_industry_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (для широкой карточки)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (для широкой карточки)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (для широкой карточки)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (для широкой карточки)'),
        ),
    ]
