# Generated by Django 5.2 on 2026-05-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_stat_description_stat_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_id',
            field=models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=20, verbose_name='Google Analytics 4 ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gsc_verification',
            field=models.CharField(blank=True, help_text='Значение content из meta google-site-verification', max_length=100, verbose_name='Google Search Console — код'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_domain',
            field=models.URLField(blank=True, help_text='https://zea.kg — для canonical, sitemap, Open Graph', verbose_name='Домен сайта'),
        ),
    ]
