# Generated by Django 5.2 on 2026-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_sitesettings_ga4_id_sitesettings_gsc_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_domain',
            field=models.URLField(blank=True, help_text='https://zeastudio.su — для canonical, sitemap, Open Graph', verbose_name='Домен сайта'),
        ),
    ]
