# Generated by Django 5.2 on 2026-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_sitesettings_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('icon', models.CharField(default='check-circle', max_length=60, verbose_name='Иконка (lucide)')),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow')], default='indigo', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Что берём на себя',
                'verbose_name_plural': 'Что мы берём на себя',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CooperationFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('audience', models.CharField(blank=True, max_length=250, verbose_name='Для кого')),
                ('audience_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Для кого')),
                ('audience_ky', models.CharField(blank=True, max_length=250, null=True, verbose_name='Для кого')),
                ('audience_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Для кого')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('terms', models.CharField(blank=True, help_text='Без процентов и сумм — условия обсуждаются индивидуально', max_length=250, verbose_name='Условия (строка внизу)')),
                ('terms_ru', models.CharField(blank=True, help_text='Без процентов и сумм — условия обсуждаются индивидуально', max_length=250, null=True, verbose_name='Условия (строка внизу)')),
                ('terms_ky', models.CharField(blank=True, help_text='Без процентов и сумм — условия обсуждаются индивидуально', max_length=250, null=True, verbose_name='Условия (строка внизу)')),
                ('terms_en', models.CharField(blank=True, help_text='Без процентов и сумм — условия обсуждаются индивидуально', max_length=250, null=True, verbose_name='Условия (строка внизу)')),
                ('cta_label', models.CharField(max_length=60, verbose_name='Текст кнопки')),
                ('cta_label_ru', models.CharField(max_length=60, null=True, verbose_name='Текст кнопки')),
                ('cta_label_ky', models.CharField(max_length=60, null=True, verbose_name='Текст кнопки')),
                ('cta_label_en', models.CharField(max_length=60, null=True, verbose_name='Текст кнопки')),
                ('request_type', models.CharField(choices=[('partnership', 'Хочу обсудить партнёрство'), ('development', 'Нужна разработка'), ('other', 'Другой вопрос')], default='partnership', help_text='Кнопка открывает форму с этим типом обращения', max_length=20, verbose_name='Тип обращения в форме')),
                ('icon', models.CharField(default='handshake', max_length=60, verbose_name='Иконка (lucide)')),
                ('is_primary', models.BooleanField(default=False, help_text='Выделяется визуально', verbose_name='Основной формат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Формат сотрудничества',
                'verbose_name_plural': 'Форматы сотрудничества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Шаг работы',
                'verbose_name_plural': 'Как мы начинаем работу',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': 'Партнёр сайта (логотип)', 'verbose_name_plural': 'Партнёры сайта (логотипы)'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Проект сайта (кейс)', 'verbose_name_plural': 'Проекты сайта (кейсы)'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывается первым и в карточках первого экрана', verbose_name='Избранный кейс'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, help_text='Только подтверждённый результат', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_en',
            field=models.TextField(blank=True, help_text='Только подтверждённый результат', null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_ky',
            field=models.TextField(blank=True, help_text='Только подтверждённый результат', null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_ru',
            field=models.TextField(blank=True, help_text='Только подтверждённый результат', null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='Что сделали', verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_en',
            field=models.TextField(blank=True, help_text='Что сделали', null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_ky',
            field=models.TextField(blank=True, help_text='Что сделали', null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_ru',
            field=models.TextField(blank=True, help_text='Что сделали', null=True, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.TextField(blank=True, help_text='Какую задачу бизнеса решали', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_en',
            field=models.TextField(blank=True, help_text='Какую задачу бизнеса решали', null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_ky',
            field=models.TextField(blank=True, help_text='Какую задачу бизнеса решали', null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_ru',
            field=models.TextField(blank=True, help_text='Какую задачу бизнеса решали', null=True, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='stat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='ZEA создаёт цифровые продукты и системы для бизнеса — от сайтов и внутренних платформ до CRM, мобильных приложений и автоматизации. Мы не заканчиваем работу после запуска: сопровождаем продукт, развиваем его и адаптируем под новые задачи компании.', verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(default='ZEA создаёт цифровые продукты и системы для бизнеса — от сайтов и внутренних платформ до CRM, мобильных приложений и автоматизации. Мы не заканчиваем работу после запуска: сопровождаем продукт, развиваем его и адаптируем под новые задачи компании.', null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text_ky',
            field=models.TextField(default='ZEA создаёт цифровые продукты и системы для бизнеса — от сайтов и внутренних платформ до CRM, мобильных приложений и автоматизации. Мы не заканчиваем работу после запуска: сопровождаем продукт, развиваем его и адаптируем под новые задачи компании.', null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(default='ZEA создаёт цифровые продукты и системы для бизнеса — от сайтов и внутренних платформ до CRM, мобильных приложений и автоматизации. Мы не заканчиваем работу после запуска: сопровождаем продукт, развиваем его и адаптируем под новые задачи компании.', null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Пусто — кнопка не показывается', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Пусто — «© <текущий год> ZEA»', max_length=200, verbose_name='Текст подвала'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.CharField(blank=True, help_text='Пусто — «© <текущий год> ZEA»', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_ky',
            field=models.CharField(blank=True, help_text='Пусто — «© <текущий год> ZEA»', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.CharField(blank=True, help_text='Пусто — «© <текущий год> ZEA»', max_length=200, null=True, verbose_name='Текст подвала'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge',
            field=models.CharField(default='Технологический партнёр для бизнеса', max_length=100, verbose_name='Hero бейдж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge_en',
            field=models.CharField(default='Технологический партнёр для бизнеса', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge_ky',
            field=models.CharField(default='Технологический партнёр для бизнеса', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge_ru',
            field=models.CharField(default='Технологический партнёр для бизнеса', max_length=100, null=True, verbose_name='Hero бейдж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Проектируем, разрабатываем, запускаем и сопровождаем цифровые продукты. Работаем как ваша IT-команда: долгосрочно или под конкретную задачу.', verbose_name='Hero подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Проектируем, разрабатываем, запускаем и сопровождаем цифровые продукты. Работаем как ваша IT-команда: долгосрочно или под конкретную задачу.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_ky',
            field=models.TextField(default='Проектируем, разрабатываем, запускаем и сопровождаем цифровые продукты. Работаем как ваша IT-команда: долгосрочно или под конкретную задачу.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.TextField(default='Проектируем, разрабатываем, запускаем и сопровождаем цифровые продукты. Работаем как ваша IT-команда: долгосрочно или под конкретную задачу.', null=True, verbose_name='Hero подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='ZEA — технологический партнёр для бизнеса', max_length=200, verbose_name='Hero заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='ZEA — технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_ky',
            field=models.CharField(default='ZEA — технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(default='ZEA — технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Hero заголовок (H1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Пусто — кнопка не показывается', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='Технологический партнёр для бизнеса', max_length=200, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline_en',
            field=models.CharField(blank=True, default='Технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline_ky',
            field=models.CharField(blank=True, default='Технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline_ru',
            field=models.CharField(blank=True, default='Технологический партнёр для бизнеса', max_length=200, null=True, verbose_name='Слоган / подзаголовок бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Пусто — кнопка не показывается', verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Формат: https://wa.me/996XXXXXXXXX. Пусто — не показывается', verbose_name='WhatsApp URL'),
        ),
    ]
