# Generated by Django 5.2 on 2026-10-09 18:26

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_seed_partnership_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Роль')),
                ('role_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Роль')),
                ('role_ky', models.CharField(blank=True, max_length=120, null=True, verbose_name='Роль')),
                ('role_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Роль')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', help_text='Вертикальное фото 4:5 (600×750). Пусто — инициалы', keep_meta=True, null=True, quality=86, scale=None, size=[600, 750], upload_to='team/', verbose_name='📷 Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Человек в команде',
                'verbose_name_plural': 'Команда (на сайте)',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='illustration',
            field=models.CharField(blank=True, choices=[('websites', 'Сайты'), ('platforms', 'Веб-системы и платформы'), ('crm', 'CRM и внутренние системы'), ('mobile', 'Мобильные приложения'), ('automation', 'Автоматизация'), ('integrations', 'Интеграции'), ('support', 'Сопровождение'), ('ai', 'AI и ассистенты'), ('partnership', 'Технологическое партнёрство')], help_text='Пусто — подбирается автоматически по иконке', max_length=20, verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Команда или офис (горизонтальное, ~4:3). Пусто — показывается иллюстрация', keep_meta=True, null=True, quality=86, scale=None, size=[1400, 1050], upload_to='about/', verbose_name='📷 Фото для блока «О нас»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo_caption',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись к фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo_caption_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись к фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo_caption_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись к фото'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo_caption_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись к фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Фото вместо иллюстрации (800×600, WebP). Пусто — показывается иллюстрация', keep_meta=True, null=True, quality=88, scale=None, size=[800, 600], upload_to='services/', verbose_name='📷 Изображение услуги'),
        ),
    ]
