# Generated by Django 5.2 on 2026-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_seed_ai_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationformat',
            name='illustration',
            field=models.CharField(blank=True, choices=[('partnership', 'Сцепленные кольца — одна команда надолго'), ('revenue_share', 'Рост дохода и доля ZEA — партнёрство за процент'), ('development', 'Этапы до сдачи — проект под заказ')], help_text='Пусто — автоматически: основной формат — кольца, иконка «рост» или «доллар» — доля в доходе, разработка — этапы до сдачи', max_length=20, verbose_name='Иллюстрация'),
        ),
    ]
