# Generated by Django 5.2 on 2026-10-09 19:33

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_format_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Реальный скриншот платформы (без вымышленных данных)', keep_meta=True, quality=85, scale=None, size=[1800, 2400], upload_to='projects/gallery/', verbose_name='📷 Скриншот')),
                ('kind', models.CharField(choices=[('desktop', 'Компьютер'), ('mobile', 'Телефон')], default='desktop', help_text='Определяет рамку: окно браузера или телефон', max_length=10, verbose_name='Экран')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись')),
                ('caption_ky', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cms.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Скриншот проекта',
                'verbose_name_plural': 'Скриншоты проекта',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
