# Generated by Django 5.2 on 2026-10-09 19:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_project_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Показывается в углу обложки на главной (квадрат или прозрачный фон)', keep_meta=True, null=True, quality=90, scale=None, size=[400, 400], upload_to='projects/logos/', verbose_name='🖼 Логотип проекта'),
        ),
    ]
