# Generated by Django 5.2 on 2026-10-09 19:57

import django.db.models.deletion
from django.db import migrations, models

from apps.cms.models import make_slug


def fill_slugs(apps, schema_editor):
    """Адреса страниц для уже существующих партнёров (ничего не удаляет)."""
    Partner = apps.get_model('cms', 'Partner')
    used = set(Partner.objects.exclude(slug=None).values_list('slug', flat=True))
    for p in Partner.objects.filter(slug=None).order_by('pk'):
        base = make_slug(p.name_ru or p.name)
        slug, n = base, 2
        while slug in used:
            slug, n = f'{base}-{n}', n + 1
        used.add(slug)
        p.slug = slug
        p.save(update_fields=['slug'])



class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='about',
            field=models.TextField(blank=True, help_text='Короткий текст для страницы партнёра', verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_en',
            field=models.TextField(blank=True, help_text='Короткий текст для страницы партнёра', null=True, verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_ky',
            field=models.TextField(blank=True, help_text='Короткий текст для страницы партнёра', null=True, verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_ru',
            field=models.TextField(blank=True, help_text='Короткий текст для страницы партнёра', null=True, verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, help_text='zeastudio.su/partners/<адрес>/. Пусто — из названия', max_length=80, null=True, unique=True, verbose_name='Адрес страницы'),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт партнёра'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Проект покажется на странице этого партнёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cms.partner', verbose_name='Партнёр (заказчик)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='kind',
            field=models.CharField(choices=[('desktop', 'Компьютер'), ('mobile', 'Телефон'), ('image', 'Изображение (квадрат)')], default='desktop', help_text='Рамка: окно браузера, телефон или просто изображение (промо, баннер)', max_length=10, verbose_name='Экран'),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
    ]
