# Generated by Django 5.2 on 2026-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_partner_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='quote',
            field=models.TextField(blank=True, help_text='Только реальный отзыв, с согласия партнёра', verbose_name='Отзыв партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_author',
            field=models.CharField(blank=True, help_text='Например: Айгерим, директор', max_length=120, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_author_en',
            field=models.CharField(blank=True, help_text='Например: Айгерим, директор', max_length=120, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_author_ky',
            field=models.CharField(blank=True, help_text='Например: Айгерим, директор', max_length=120, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_author_ru',
            field=models.CharField(blank=True, help_text='Например: Айгерим, директор', max_length=120, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_en',
            field=models.TextField(blank=True, help_text='Только реальный отзыв, с согласия партнёра', null=True, verbose_name='Отзыв партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_ky',
            field=models.TextField(blank=True, help_text='Только реальный отзыв, с согласия партнёра', null=True, verbose_name='Отзыв партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_ru',
            field=models.TextField(blank=True, help_text='Только реальный отзыв, с согласия партнёра', null=True, verbose_name='Отзыв партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='since',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — год самого раннего общего проекта', null=True, verbose_name='Партнёр с (год)'),
        ),
    ]
