# Generated by Django 5.2 on 2026-10-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_partner_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, help_text='https://www.instagram.com/<аккаунт>/ — лента покажется на странице партнёра', verbose_name='Instagram'),
        ),
    ]
