# Generated by Django 5.2 on 2026-09-28 17:59

import apps.contracts.models
import apps.hub.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.CharField(max_length=64, verbose_name='Номер договора')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('ready', 'Готов к подписанию'), ('active', 'Действует'), ('expired', 'Истёк'), ('terminated', 'Расторгнут')], db_index=True, default='draft', editable=False, max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Статус изменён')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Пусто — бессрочный', null=True, verbose_name='Дата окончания')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Процент ZEA')),
                ('calculation_base_type', models.CharField(blank=True, choices=[('total_revenue', 'Общая выручка компании'), ('product_revenue', 'Выручка продукта / направления'), ('system_revenue', 'Продажи через созданную ZEA систему'), ('profit', 'Прибыль'), ('other', 'Другая договорная база')], max_length=30, verbose_name='База расчёта')),
                ('calculation_base_description', models.TextField(blank=True, help_text='От чего именно ZEA получает процент, как в договоре. Обязательно для «Другая».', verbose_name='База расчёта — точная формулировка')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Условия оплаты')),
                ('zea_obligations', models.TextField(blank=True, verbose_name='Обязанности ZEA')),
                ('partner_obligations', models.TextField(blank=True, verbose_name='Обязанности партнёра')),
                ('termination_terms', models.TextField(blank=True, verbose_name='Условия прекращения')),
                ('additional_terms', models.TextField(blank=True, verbose_name='Дополнительные условия')),
                ('file', models.FileField(blank=True, max_length=255, storage=apps.hub.storage.private_storage, upload_to=apps.contracts.models.contract_file_path, verbose_name='Файл договора (PDF)')),
                ('file_original_name', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Имя файла')),
                ('file_uploaded_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Файл загружен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='partners.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('appendix', 'Приложение к договору'), ('supplement', 'Дополнительное соглашение'), ('spec', 'Техническое задание'), ('act', 'Акт'), ('other', 'Другой документ')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(max_length=255, storage=apps.hub.storage.private_storage, upload_to=apps.contracts.models.contract_document_path, verbose_name='Файл')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Имя файла')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='Размер, байт')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Загружен')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Договор')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ договора',
                'verbose_name_plural': 'Документы договоров',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('ready', 'Готов к подписанию'), ('active', 'Действует'), ('expired', 'Истёк'), ('terminated', 'Расторгнут')], max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('ready', 'Готов к подписанию'), ('active', 'Действует'), ('expired', 'Истёк'), ('terminated', 'Расторгнут')], max_length=20, verbose_name='В статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Изменение статуса договора',
                'verbose_name_plural': 'История статусов договоров',
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('number',), name='contracts_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company',), name='contracts_one_active_per_company'),
        ),
    ]
