# Generated by Django 5.2 on 2026-09-28 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_technical', models.BooleanField(default=True, help_text='Участников с технической специализацией может добавлять в проект технический руководитель проекта.', verbose_name='Техническая')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contractor', 'Подрядчик / фриланс')], default='full_time', max_length=20, verbose_name='Тип работы')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает в команде')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('specializations', models.ManyToManyField(blank=True, related_name='employees', to='team.specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
            },
        ),
    ]
