# Generated by Django 5.2 on 2026-09-28 18:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('partners', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9-]*$', 'Код: заглавные латинские буквы, цифры и дефис, например KE-CRM.')], verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('project_type', models.CharField(choices=[('website', 'Сайт'), ('web_system', 'Веб-система'), ('mobile_app', 'Мобильное приложение'), ('crm', 'CRM / внутренняя система'), ('automation', 'Автоматизация'), ('integration', 'Интеграция'), ('other', 'Другое')], max_length=20, verbose_name='Тип проекта')),
                ('project_type_other', models.CharField(blank=True, help_text='Обязательно для типа «Другое».', max_length=150, verbose_name='Тип — описание')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('mvp', 'MVP'), ('launched', 'Запущен'), ('support', 'Сопровождение'), ('paused', 'Приостановлен'), ('cancelled', 'Отменён')], db_index=True, default='planning', editable=False, max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Статус изменён')),
                ('paused_from_status', models.CharField(blank=True, choices=[('planning', 'Планирование'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('mvp', 'MVP'), ('launched', 'Запущен'), ('support', 'Сопровождение'), ('paused', 'Приостановлен'), ('cancelled', 'Отменён')], editable=False, max_length=20, verbose_name='Статус до паузы')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критичный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Плановое завершение')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическое завершение')),
                ('launch_date', models.DateField(blank=True, editable=False, help_text='Проставляется при первом переходе в «Запущен».', null=True, verbose_name='Дата запуска')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='partners.company', verbose_name='Компания')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='PM')),
                ('technical_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Технический руководитель')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='В проекте с')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Вышел из проекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='Проект')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='team.specialization', verbose_name='Роль в проекте')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
                'ordering': ('-is_active', 'joined_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('planning', 'Планирование'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('mvp', 'MVP'), ('launched', 'Запущен'), ('support', 'Сопровождение'), ('paused', 'Приостановлен'), ('cancelled', 'Отменён')], max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('planning', 'Планирование'), ('development', 'Разработка'), ('testing', 'Тестирование'), ('mvp', 'MVP'), ('launched', 'Запущен'), ('support', 'Сопровождение'), ('paused', 'Приостановлен'), ('cancelled', 'Отменён')], max_length=20, verbose_name='В статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изменение статуса проекта',
                'verbose_name_plural': 'История статусов проектов',
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('repository_url', models.URLField(blank=True, verbose_name='Репозиторий')),
                ('production_url', models.URLField(blank=True, verbose_name='Production')),
                ('staging_url', models.URLField(blank=True, verbose_name='Staging')),
                ('technology_stack', models.TextField(blank=True, verbose_name='Стек технологий')),
                ('server_info', models.TextField(blank=True, help_text='Хостинг, регион, тип сервера — без IP-доступов и паролей.', verbose_name='Серверы и окружение')),
                ('deployment_notes', models.TextField(blank=True, verbose_name='Деплой')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Технические заметки')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_info', to='projects.project', verbose_name='Проект')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Техническая информация проекта',
                'verbose_name_plural': 'Техническая информация проектов',
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('code',), name='projects_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'member', 'specialization'), name='projects_unique_active_member_role'),
        ),
    ]
